# docker build -t debugger:latest -f Dockerfile.debugger .

FROM debian:10-slim

RUN apt update
RUN apt install -y build-essential curl pkg-config libssl-dev python3 python3-pip
RUN pip3 install virtualenv 
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y