# docker build -t runner-alpine:latest -f Dockerfiles//Alpine/Dockerfile.runner.alpine --progress=plain .

FROM alpine:3.16.2

RUN apk update
# RUN apt install -y libssl-dev python3 python3-pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN pip3 install virtualenv 

RUN apk add bash
RUN apk add gcc