version: "3.9"

networks:
  network:
    external: true
    name: network

services:
  redis:
    container_name: redis
    image: redis:latest
    networks: 
      - network
  master:
    container_name: master
    image: localhost:32000/master-release
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./Performance-Testing-Data:/home/app/Backend/Performance-Testing-Data
    ports:
      - "3000:3000"
    networks: 
      - network
  worker:
    container_name: worker
    image: localhost:32000/worker-release
    environment:
      - REDIS_HOST=redis
      - MASTER_IP=master:3000
      - WORKER_NAME=worker:5000
    volumes:
      - ./Performance-Testing-Data:/home/app/Backend/Performance-Testing-Data
    ports:
      - "5000:5000"
    networks: 
      - network
  frontend:
    container_name: frontend
    image: localhost:32000/frontend
    ports:
      - "7000:80"
    networks: 
      - network