# docker build -t frontend:latest -f Dockerfiles/Dockerfile.frontend .
# docker run --name frontend --rm -it -p 8080:80/tcp frontend:latest

# proxy and other configurations must be defined in the main proxy server or k8s ingress

FROM nginx:alpine

COPY Frontend/dist /usr/share/nginx/html