# docker build -t runner:latest -f Dockerfiles/Dockerfile.runner .

FROM debian:10-slim

RUN apt update

RUN addgroup --system app && adduser app --system --ingroup app
RUN chown app /home/app

RUN apt install -y libssl-dev python3 python3-pip libfontconfig libfontconfig1-dev

RUN pip3 install virtualenv