FROM debian:11-slim

RUN apt update
RUN apt install -y git python3 python3-dev python3-pip gcc g++ make swig curl libssl-dev libfontconfig libfontconfig1-dev

# install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# install python libs
RUN pip3 install virtualenv

COPY Cargo.lock /home/Cargo.lock
COPY Cargo.toml /home/Cargo.toml

WORKDIR /home

RUN export PATH=$PATH:/root/.cargo/bin/

ENV REDIS_HOST host.docker.internal
ENV LD_LIBRARY_PATH /usr/local/lib

EXPOSE 3000
EXPOSE 5000

# docker build -t performance-testing-dev -f Dockerfiles/Dockerfile.dev .
# docker run --name performance -it --rm -p 3000:3000/tcp -p 5000:5000/tcp --add-host=host.docker.internal:host-gateway --network net  -v ${PWD}/Backend:/home/Backend performance-testing-dev
