version: "3.9"

services:
  builder:
    container_name: builder
    image: builder
    build:
      context: ../
      dockerfile: ./Dockerfiles/Dockerfile.builder
  runner:
    container_name: runner
    image: runner
    build:
      context: ../
      dockerfile: ./Dockerfiles/Dockerfile.runner
