# docker build -t builder-alpine:latest -f Dockerfiles/Dockerfile.builder.alpine --progress=plain .

FROM alpine:3.16.2

RUN apk update
RUN apk add curl
# RUN apt install -y build-essential curl pkg-config libssl-dev libfontconfig libfontconfig1-dev
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN apk add gcc
RUN apk add alpine-sdk
RUN apk add fontconfig fontconfig-dev
RUN apk add openssl openssl-dev