apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  namespace: performance-testing
  labels:
    app: master #this label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master #this label
  template:
    metadata:
      labels:
        app: master #this label
    spec:
      securityContext:
        runAsUser: 0 #101
        runAsGroup: 0 #101
        fsGroup: 0 #101
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
      - name: task-pv-storage-lib
        persistentVolumeClaim:
          claimName: pv-claim-lib
      containers:
      - name: master
        image: localhost:32000/master-release:latest
        imagePullPolicy: "Always"
        
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: redis_host
        volumeMounts:
        - mountPath: "/home/app/Backend/Performance-Testing-Data"
          name: task-pv-storage
        - mountPath: "/usr/local/lib"
          name: task-pv-storage-lib
        securityContext:
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: performance-testing
  labels:
    app: master-service
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: master #this label
  sessionAffinity: None