---
- name: Set up Docker
  hosts: performance-testing
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt: name=docker state=present
    
    - name: Ensure docker group is there
      group: name=docker state=present

- name: Set up Microk8s
  hosts: performance-testing
  become: yes
  tasks:
    - name: Ensure Microk8s is installed
      snap: name=microk8s state=present classic=yes

    - name: Create Microk8s kubctl alias
      command: snap alias microk8s.kubectl kubectl
      register: alias
    - debug: msg="{{ alias.stdout }}"

    - name: Enable DNS
      command: microk8s enable dns
      register: dns
    - debug: msg="{{ dns.stdout }}"

    - name: Enable registry
      command: microk8s enable registry
      register: registry
    - debug: msg="{{ registry.stdout }}"

    - name: Enable Ingress
      command: microk8s enable ingress
      register: ingress
    - debug: msg="{{ ingress.stdout }}"

    - name: Enable Loadbalancing
      command: microk8s enable metallb:10.64.140.43-10.64.140.49
      register: Loadbalancing
    - debug: msg="{{ Loadbalancing.stdout }}"

# ansible-playbook setup.yaml